services:
  db:
    image: mysql:latest
    container_name: bloggin_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bloggin_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql@123
    ports:
      - "3306:3306"